/*
 * lcd_menu_coord.h
 *
 *  Created on: 08.04.2020
 *      Author: Patrick
 */

#ifndef INC_LCD_MENU_COORD_H_
#define INC_LCD_MENU_COORD_H_

#include "lcd_pixel_settings.h"

// MENU
// - VALUE
#define VALUE_LETTER_COUNT					(5)

#define VALUE_RECT_OUTER_START_X			(0)
#define VALUE_RECT_OUTER_START_Y			(0)
#define VALUE_RECT_OUTER_LENGTH_X			(LINE_WIDTH + VALUE_LETTER_COUNT * LETTER_X + SPACE + LINE_WIDTH)
#define VALUE_RECT_OUTER_LENGTH_Y			(LINE_WIDTH + LETTER_Y + SPACE + LINE_WIDTH)

#define VALUE_RECT_INNER_AXIS_X				(VALUE_RECT_OUTER_START_X + LINE_WIDTH)
#define VALUE_RECT_INNER_AXIS_Y				(VALUE_RECT_OUTER_START_Y + LINE_WIDTH)
#define VALUE_RECT_INNER_LENGTH_X			(VALUE_LETTER_COUNT * LETTER_X + SPACE)
#define VALUE_RECT_INNER_LENGTH_Y			(LETTER_Y + SPACE)

#define VALUE_NAME_AXIS_X					(VALUE_RECT_OUTER_START_X + LINE_WIDTH)
#define VALUE_NAME_AXIS_Y					(LINE_WIDTH + SPACE)

// - GRAPH
#define GRAPH_LETTER_COUNT					(5)

#define GRAPH_RECT_OUTER_AXIS_X				(VALUE_RECT_OUTER_START_X + VALUE_RECT_OUTER_LENGTH_X - LINE_WIDTH)
#define GRAPH_RECT_OUTER_AXIS_Y				(VALUE_RECT_OUTER_START_Y)
#define GRAPH_RECT_OUTER_LENGTH_X			(LINE_WIDTH + GRAPH_LETTER_COUNT * LETTER_X + SPACE + LINE_WIDTH)
#define GRAPH_RECT_OUTER_LENGTH_Y			(VALUE_RECT_OUTER_LENGTH_Y)

#define GRAPH_RECT_INNER_AXIS_X				(GRAPH_RECT_OUTER_AXIS_X + LINE_WIDTH)
#define GRAPH_RECT_INNER_AXIS_Y				(GRAPH_RECT_OUTER_AXIS_Y + LINE_WIDTH)
#define GRAPH_RECT_INNER_LENGTH_X			(GRAPH_LETTER_COUNT * LETTER_X + SPACE)
#define GRAPH_RECT_INNER_LENGTH_Y			(VALUE_RECT_INNER_LENGTH_Y)

#define GRAPH_NAME_AXIS_X					(GRAPH_RECT_OUTER_AXIS_X + LINE_WIDTH)
#define GRAPH_NAME_AXIS_Y					(VALUE_NAME_AXIS_Y)

// - SETTINGS
#define SETTINGS_LETTER_COUNT				(8)

#define SETTINGS_RECT_OUTER_AXIS_X			(GRAPH_RECT_OUTER_AXIS_X + GRAPH_RECT_OUTER_LENGTH_X - LINE_WIDTH)
#define SETTINGS_RECT_OUTER_AXIS_Y			(GRAPH_RECT_OUTER_AXIS_Y)
#define SETTINGS_RECT_OUTER_LENGTH_X		(LINE_WIDTH + SETTINGS_LETTER_COUNT * LETTER_X + SPACE + LINE_WIDTH)
#define SETTINGS_RECT_OUTER_LENGTH_Y		(GRAPH_RECT_OUTER_LENGTH_Y)

#define SETTINGS_RECT_INNER_AXIS_X			(SETTINGS_RECT_OUTER_AXIS_X + LINE_WIDTH)
#define SETTINGS_RECT_INNER_AXIS_Y			(SETTINGS_RECT_OUTER_AXIS_Y + LINE_WIDTH)
#define SETTINGS_RECT_INNER_LENGTH_X		(SETTINGS_LETTER_COUNT * LETTER_X + SPACE)
#define SETTINGS_RECT_INNER_LENGTH_Y		(GRAPH_RECT_INNER_LENGTH_Y)

#define SETTINGS_NAME_AXIS_X				(SETTINGS_RECT_OUTER_AXIS_X + LINE_WIDTH)
#define SETTINGS_NAME_AXIS_Y				(GRAPH_NAME_AXIS_Y)

// - DEBUG
#define DEBUG_LETTER_COUNT					(5)

#define DEBUG_RECT_OUTER_AXIS_X				(SETTINGS_RECT_OUTER_AXIS_X + SETTINGS_RECT_OUTER_LENGTH_X - LINE_WIDTH)
#define DEBUG_RECT_OUTER_AXIS_Y				(SETTINGS_RECT_OUTER_AXIS_Y)
#define DEBUG_RECT_OUTER_LENGTH_X			(LINE_WIDTH + DEBUG_LETTER_COUNT * LETTER_X + SPACE + LINE_WIDTH)
#define DEBUG_RECT_OUTER_LENGTH_Y			(SETTINGS_RECT_OUTER_LENGTH_Y)

#define DEBUG_RECT_INNER_AXIS_X				(DEBUG_RECT_OUTER_AXIS_X + LINE_WIDTH)
#define DEBUG_RECT_INNER_AXIS_Y				(DEBUG_RECT_OUTER_AXIS_Y + LINE_WIDTH)
#define DEBUG_RECT_INNER_LENGTH_X			(DEBUG_LETTER_COUNT * LETTER_X + SPACE)
#define DEBUG_RECT_INNER_LENGTH_Y			(SETTINGS_RECT_INNER_LENGTH_Y)

#define DEBUG_NAME_AXIS_X					(DEBUG_RECT_OUTER_AXIS_X + LINE_WIDTH)
#define DEBUG_NAME_AXIS_Y					(SETTINGS_NAME_AXIS_Y)

// - VALUE - VALUE BOXES
#define VALUE_INFO_LETTER_COUNT				(6)
#define VALUE_RECT_LETTER_COUNT				(9)

#define VALUE_BOX_SPACE						(1)

#define VALUE_COL1_TEXT_START_X				(0 + LINE_WIDTH)
#define VALUE_COL1_TEXT_START_Y				(20 + LINE_WIDTH + SPACE)

#define VALUE_COL2_TEXT_START_X				(15 * 8 + LINE_WIDTH)
#define VALUE_COL2_TEXT_START_Y				(20 + LINE_WIDTH + SPACE)

#define VALUE_INFO_LENGTH_X					(LINE_WIDTH + VALUE_INFO_LETTER_COUNT * LETTER_X + SPACE + LINE_WIDTH)
#define VALUE_INFO_LENGTH_Y					(LINE_WIDTH + SPACE + LETTER_Y + LINE_WIDTH)

#define VALUE_COL1_RECT_START_X				(VALUE_COL1_TEXT_START_X + VALUE_INFO_LENGTH_X)
#define VALUE_COL1_RECT_START_Y				(20)

#define VALUE_COL1_NUMBER_START_X				(VALUE_COL1_RECT_START_X + LINE_WIDTH)
#define VALUE_COL1_NUMBER_START_Y				(VALUE_COL1_TEXT_START_Y)

#define VALUE_COL2_RECT_START_X				(VALUE_COL2_TEXT_START_X + VALUE_INFO_LENGTH_X)
#define VALUE_COL2_RECT_START_Y				(20)

#define VALUE_COL2_NUMBER_START_X				(VALUE_COL2_RECT_START_X + LINE_WIDTH)
#define VALUE_COL2_NUMBER_START_Y				(VALUE_COL2_TEXT_START_Y)

#define VALUE_RECT_LENGTH_X					(LINE_WIDTH + VALUE_RECT_LETTER_COUNT * LETTER_X + SPACE + LINE_WIDTH)
#define VALUE_RECT_LENGTH_Y					(LINE_WIDTH + SPACE + LETTER_Y + LINE_WIDTH)


// - SETTINGS - MEASURE
#define SETT_MEASURE_LETTER					(7)
#define SETT_MEASURE_OFFSET					(SETT_MEASURE_LETTER * LETTER_X)

// - SETTINGS - MEASURE START
#define SETT_START_LETTER					(5)
#define SETT_START_LETTER_COUNT				(SETT_MEASURE_LETTER + SPACE + SETT_START_LETTER + SPACE)

#define SETT_START_RECT_START_X				(0)
#define SETT_START_RECT_START_Y				(20)

#define SETT_START_RECT_LENGTH_X			(LINE_WIDTH + SETT_START_LETTER_COUNT * LETTER_X + SPACE + LINE_WIDTH)
#define SETT_START_RECT_LENGTH_Y			(LINE_WIDTH + SPACE + LETTER_Y + LINE_WIDTH)

#define SETT_START_TEXT_START_X				(SETT_START_RECT_START_X + LINE_WIDTH)
#define SETT_START_TEXT_START_Y				(SETT_START_RECT_START_Y + LINE_WIDTH + SPACE)

// - SETTINGS - MEASURE START BUTTON
#define SETT_START_LEFT_START_X				(BODY_SUB_HOME_X)
#define SETT_START_LEFT_START_Y				(SETT_START_RECT_START_Y)

#define SETT_START_LEFT_LENGTH_X			(LINE_WIDTH + 2 * LETTER_X + SPACE + LINE_WIDTH)
#define SETT_START_LEFT_LENGTH_Y			(SETT_START_RECT_LENGTH_Y)

#define SETT_START_RIGHT_START_X			(SETT_START_LEFT_START_X + SETT_START_LEFT_LENGTH_X - 1)
#define SETT_START_RIGHT_START_Y			(SETT_START_RECT_START_Y)

#define SETT_START_RIGHT_LENGTH_X			(SETT_START_LEFT_LENGTH_X)
#define SETT_START_RIGHT_LENGTH_Y			(SETT_START_LEFT_LENGTH_Y)

// - SETTINGS - MEASURE PAUSE
#define SETT_PAUSE_LETTER					(5)
#define SETT_PAUSE_LETTER_COUNT				(SETT_MEASURE_LETTER + SPACE + SETT_PAUSE_LETTER + SPACE)

#define SETT_PAUSE_RECT_START_X				(SETT_START_RECT_START_X)
#define SETT_PAUSE_RECT_START_Y				(SETT_START_RECT_START_Y + SETT_START_RECT_LENGTH_Y + SPACE)

#define SETT_PAUSE_RECT_LENGTH_X			(LINE_WIDTH + SETT_PAUSE_LETTER_COUNT * LETTER_X + SPACE + LINE_WIDTH)
#define SETT_PAUSE_RECT_LENGTH_Y			(LINE_WIDTH + SPACE + LETTER_Y + LINE_WIDTH)

#define SETT_PAUSE_TEXT_START_X				(SETT_PAUSE_RECT_START_X + LINE_WIDTH)
#define SETT_PAUSE_TEXT_START_Y				(SETT_PAUSE_RECT_START_Y + LINE_WIDTH + SPACE)

// - SETTINGS - MEASURE STOP
#define SETT_STOP_LETTER					(4)
#define SETT_STOP_LETTER_COUNT				(SETT_MEASURE_LETTER + SPACE + SETT_STOP_LETTER + 2 * SPACE)

#define SETT_STOP_RECT_START_X				(SETT_PAUSE_RECT_START_X)
#define SETT_STOP_RECT_START_Y				(SETT_PAUSE_RECT_START_Y + SETT_PAUSE_RECT_LENGTH_Y + SPACE)

#define SETT_STOP_RECT_LENGTH_X				(LINE_WIDTH + SETT_STOP_LETTER_COUNT * LETTER_X + SPACE + LINE_WIDTH)
#define SETT_STOP_RECT_LENGTH_Y				(LINE_WIDTH + SPACE + LETTER_Y + LINE_WIDTH)

#define SETT_STOP_TEXT_START_X				(SETT_STOP_RECT_START_X + LINE_WIDTH)
#define SETT_STOP_TEXT_START_Y				(SETT_STOP_RECT_START_Y + LINE_WIDTH + SPACE)

// - SETTINGS - MEASURE PERIOD
#define SETT_PERIOD_LETTER					(6)
#define SETT_PERIOD_LETTER_COUNT			(SETT_MEASURE_LETTER + SPACE + SETT_PERIOD_LETTER)

#define SETT_PERIOD_RECT_START_X			(SETT_STOP_RECT_START_X)
#define SETT_PERIOD_RECT_START_Y			(SETT_STOP_RECT_START_Y + SETT_STOP_RECT_LENGTH_Y + SPACE)

#define SETT_PERIOD_RECT_LENGTH_X			(LINE_WIDTH + SETT_PERIOD_LETTER_COUNT * LETTER_X + SPACE + LINE_WIDTH)
#define SETT_PERIOD_RECT_LENGTH_Y			(LINE_WIDTH + SPACE + LETTER_Y + LINE_WIDTH)

#define SETT_PERIOD_TEXT_START_X			(SETT_PERIOD_RECT_START_X + LINE_WIDTH)
#define SETT_PERIOD_TEXT_START_Y			(SETT_PERIOD_RECT_START_Y + LINE_WIDTH + SPACE)

// - SETTINGS - MEASURE PERIOD BUTTON
#define SETT_PERIOD_BUTTON_START_X			(BODY_SUB_HOME_X)
#define SETT_PERIOD_BUTTON_START_Y			(SETT_PERIOD_RECT_START_Y)

#define SETT_PERIOD_BUTTON_LENGTH_X			(LINE_WIDTH + 7 * LETTER_X + SPACE + LINE_WIDTH)
#define SETT_PERIOD_BUTTON_LENGTH_Y			(SETT_PERIOD_RECT_LENGTH_Y)

// - SETTINGS - FLIP TEXT
#define SETT_FLIP_LETTER_COUNT				(14)

#define SETT_FLIP_RECT_START_X				(SETT_PERIOD_RECT_START_X)
#define SETT_FLIP_RECT_START_Y				(SETT_PERIOD_RECT_START_Y + SETT_PERIOD_RECT_LENGTH_Y + SPACE)

#define SETT_FLIP_RECT_LENGTH_X				(LINE_WIDTH + SETT_FLIP_LETTER_COUNT * LETTER_X + SPACE + LINE_WIDTH)
#define SETT_FLIP_RECT_LENGTH_Y				(LINE_WIDTH + SPACE + LETTER_Y + LINE_WIDTH)

#define SETT_FLIP_TEXT_START_X				(SETT_FLIP_RECT_START_X + LINE_WIDTH)
#define SETT_FLIP_TEXT_START_Y				(SETT_FLIP_RECT_START_Y + LINE_WIDTH + SPACE)

// - SETTINGS - FLIP BUTTON
#define SETT_FLIP_LEFT_START_X				(BODY_SUB_HOME_X)
#define SETT_FLIP_LEFT_START_Y				(SETT_FLIP_RECT_START_Y)

#define SETT_FLIP_LEFT_LENGTH_X				(LINE_WIDTH + 4 * LETTER_X + SPACE + LINE_WIDTH)
#define SETT_FLIP_LEFT_LENGTH_Y				(SETT_FLIP_RECT_LENGTH_Y)

#define SETT_FLIP_RIGHT_START_X				(SETT_FLIP_LEFT_START_X + SETT_FLIP_LEFT_LENGTH_X - 1)
#define SETT_FLIP_RIGHT_START_Y				(SETT_FLIP_RECT_START_Y)

#define SETT_FLIP_RIGHT_LENGTH_X			(SETT_FLIP_LEFT_LENGTH_X)
#define SETT_FLIP_RIGHT_LENGTH_Y			(SETT_START_LEFT_LENGTH_Y)

#endif /* INC_LCD_MENU_COORD_H_ */
